/* eslint-disable global-require */
export default {
  "Apple iPad Air 2 Gold": require("./FacebookDevices/Apple iPad Air 2 Gold.png"),
  "Apple iPad Air 2 Silver": require("./FacebookDevices/Apple iPad Air 2 Silver.png"),
  "Apple iPad Air 2 Space Gray": require("./FacebookDevices/Apple iPad Air 2 Space Gray.png"),
  "Apple iPad Mini 4 Gold": require("./FacebookDevices/Apple iPad Mini 4 Gold.png"),
  "Apple iPad Mini 4 Silver": require("./FacebookDevices/Apple iPad Mini 4 Silver.png"),
  "Apple iPad Mini 4 Space Gray": require("./FacebookDevices/Apple iPad Mini 4 Space Gray.png"),
  "Apple iPad Pro Gold": require("./FacebookDevices/Apple iPad Pro Gold.png"),
  "Apple iPad Pro Silver": require("./FacebookDevices/Apple iPad Pro Silver.png"),
  "Apple iPad Pro Space Gray": require("./FacebookDevices/Apple iPad Pro Space Gray.png"),
  "Apple iPhone 5c Blue": require("./FacebookDevices/Apple iPhone 5c Blue.png"),
  "Apple iPhone 5c Green": require("./FacebookDevices/Apple iPhone 5c Green.png"),
  "Apple iPhone 5c Red": require("./FacebookDevices/Apple iPhone 5c Red.png"),
  "Apple iPhone 5c White": require("./FacebookDevices/Apple iPhone 5c White.png"),
  "Apple iPhone 5c Yellow": require("./FacebookDevices/Apple iPhone 5c Yellow.png"),
  "Apple iPhone 5s Gold": require("./FacebookDevices/Apple iPhone 5s Gold.png"),
  "Apple iPhone 5s Silver": require("./FacebookDevices/Apple iPhone 5s Silver.png"),
  "Apple iPhone 5s Space Gray": require("./FacebookDevices/Apple iPhone 5s Space Gray.png"),
  "Apple iPhone 6s Gold": require("./FacebookDevices/Apple iPhone 6s Gold.png"),
  "Apple iPhone 6s Plus Gold": require("./FacebookDevices/Apple iPhone 6s Plus Gold.png"),
  "Apple iPhone 6s Plus Rose Gold": require("./FacebookDevices/Apple iPhone 6s Plus Rose Gold.png"),
  "Apple iPhone 6s Plus Silver": require("./FacebookDevices/Apple iPhone 6s Plus Silver.png"),
  "Apple iPhone 6s Plus Space Gray": require("./FacebookDevices/Apple iPhone 6s Plus Space Gray.png"),
  "Apple iPhone 6s Rose Gold": require("./FacebookDevices/Apple iPhone 6s Rose Gold.png"),
  "Apple iPhone 6s Silver": require("./FacebookDevices/Apple iPhone 6s Silver.png"),
  "Apple iPhone 6s Space Gray": require("./FacebookDevices/Apple iPhone 6s Space Gray.png"),
  "Apple iPhone 7 Gold": require("./FacebookDevices/Apple iPhone 7 Gold.png"),
  "Apple iPhone 7 Jet Black": require("./FacebookDevices/Apple iPhone 7 Jet Black.png"),
  "Apple iPhone 7 Matte Black": require("./FacebookDevices/Apple iPhone 7 Matte Black.png"),
  "Apple iPhone 7 Plus Gold": require("./FacebookDevices/Apple iPhone 7 Plus Gold.png"),
  "Apple iPhone 7 Plus Jet Black": require("./FacebookDevices/Apple iPhone 7 Plus Jet Black.png"),
  "Apple iPhone 7 Plus Matte Black": require("./FacebookDevices/Apple iPhone 7 Plus Matte Black.png"),
  "Apple iPhone 7 Plus Rose Gold": require("./FacebookDevices/Apple iPhone 7 Plus Rose Gold.png"),
  "Apple iPhone 7 Plus Silver": require("./FacebookDevices/Apple iPhone 7 Plus Silver.png"),
  "Apple iPhone 7 Rose Gold": require("./FacebookDevices/Apple iPhone 7 Rose Gold.png"),
  "Apple iPhone 7 Silver": require("./FacebookDevices/Apple iPhone 7 Silver.png"),
  "Apple iPhone 8 Gold": require("./FacebookDevices/Apple iPhone 8 Gold.png"),
  "Apple iPhone 8 Plus Gold": require("./FacebookDevices/Apple iPhone 8 Plus Gold.png"),
  "Apple iPhone 8 Plus Silver": require("./FacebookDevices/Apple iPhone 8 Plus Silver.png"),
  "Apple iPhone 8 Plus Space Gray": require("./FacebookDevices/Apple iPhone 8 Plus Space Grey.png"),
  "Apple iPhone 8 Silver": require("./FacebookDevices/Apple iPhone 8 Silver.png"),
  "Apple iPhone 8 Space Gray": require("./FacebookDevices/Apple iPhone 8 Space Grey.png"),
  "Apple iPhone SE Gold": require("./FacebookDevices/Apple iPhone SE Gold.png"),
  "Apple iPhone SE Rose Gold": require("./FacebookDevices/Apple iPhone SE Rose Gold.png"),
  "Apple iPhone SE Silver": require("./FacebookDevices/Apple iPhone SE Silver.png"),
  "Apple iPhone SE Space Gray": require("./FacebookDevices/Apple iPhone SE Space Gray.png"),
  "Apple iPhone X Silver": require("./FacebookDevices/Apple iPhone X Silver.png"),
  "Apple iPhone X Space Gray": require("./FacebookDevices/Apple iPhone X Space Grey.png"),
  "Apple iPhone XR Blue": require("./FacebookDevices/Apple iPhone XR Blue.png"),
  "Apple iPhone XR Coral": require("./FacebookDevices/Apple iPhone XR Coral.png"),
  "Apple iPhone XR Red": require("./FacebookDevices/Apple iPhone XR Red.png"),
  "Apple iPhone XR Silver": require("./FacebookDevices/Apple iPhone XR Silver.png"),
  "Apple iPhone XR Space Gray": require("./FacebookDevices/Apple iPhone XR Space Grey.png"),
  "Apple iPhone XR Yellow": require("./FacebookDevices/Apple iPhone XR Yellow.png"),
  "Apple iPhone XS Gold": require("./FacebookDevices/Apple iPhone XS Gold.png"),
  "Apple iPhone XS Max Gold": require("./FacebookDevices/Apple iPhone XS Max Gold.png"),
  "Apple iPhone XS Max Silver": require("./FacebookDevices/Apple iPhone XS Max Silver.png"),
  "Apple iPhone XS Max Space Gray": require("./FacebookDevices/Apple iPhone XS Max Space Grey.png"),
  "Apple iPhone XS Silver": require("./FacebookDevices/Apple iPhone XS Silver.png"),
  "Apple iPhone XS Space Gray": require("./FacebookDevices/Apple iPhone XS Space Grey.png")
};
