/* eslint-disable global-require */
export default {
  "Apple iPad Air 2 Gold": require("./FacebookDevices/Apple-iPad-Air-2-Gold.png"),
  "Apple iPad Air 2 Silver": require("./FacebookDevices/Apple-iPad-Air-2-Silver.png"),
  "Apple iPad Air 2 Space Gray": require("./FacebookDevices/Apple-iPad-Air-2-Space-Gray.png"),
  "Apple iPad Mini 4 Gold": require("./FacebookDevices/Apple-iPad-Mini-4-Gold.png"),
  "Apple iPad Mini 4 Silver": require("./FacebookDevices/Apple-iPad-Mini-4-Silver.png"),
  "Apple iPad Mini 4 Space Gray": require("./FacebookDevices/Apple-iPad-Mini-4-Space-Gray.png"),
  "Apple iPad Pro Gold": require("./FacebookDevices/Apple-iPad-Pro-Gold.png"),
  "Apple iPad Pro Silver": require("./FacebookDevices/Apple-iPad-Pro-Silver.png"),
  "Apple iPad Pro Space Gray": require("./FacebookDevices/Apple-iPad-Pro-Space-Gray.png"),
  "Apple iPhone 5c Blue": require("./FacebookDevices/Apple-iPhone-5c-Blue.png"),
  "Apple iPhone 5c Green": require("./FacebookDevices/Apple-iPhone-5c-Green.png"),
  "Apple iPhone 5c Red": require("./FacebookDevices/Apple-iPhone-5c-Red.png"),
  "Apple iPhone 5c White": require("./FacebookDevices/Apple-iPhone-5c-White.png"),
  "Apple iPhone 5c Yellow": require("./FacebookDevices/Apple-iPhone-5c-Yellow.png"),
  "Apple iPhone 5s Gold": require("./FacebookDevices/Apple-iPhone-5s-Gold.png"),
  "Apple iPhone 5s Silver": require("./FacebookDevices/Apple-iPhone-5s-Silver.png"),
  "Apple iPhone 5s Space Gray": require("./FacebookDevices/Apple-iPhone-5s-Space-Gray.png"),
  "Apple iPhone 6s Gold": require("./FacebookDevices/Apple-iPhone-6s-Gold.png"),
  "Apple iPhone 6s Plus Gold": require("./FacebookDevices/Apple-iPhone-6s-Plus-Gold.png"),
  "Apple iPhone 6s Plus Rose Gold": require("./FacebookDevices/Apple-iPhone-6s-Plus-Rose-Gold.png"),
  "Apple iPhone 6s Plus Silver": require("./FacebookDevices/Apple-iPhone-6s-Plus-Silver.png"),
  "Apple iPhone 6s Plus Space Gray": require("./FacebookDevices/Apple-iPhone-6s-Plus-Space-Gray.png"),
  "Apple iPhone 6s Rose Gold": require("./FacebookDevices/Apple-iPhone-6s-Rose-Gold.png"),
  "Apple iPhone 6s Silver": require("./FacebookDevices/Apple-iPhone-6s-Silver.png"),
  "Apple iPhone 6s Space Gray": require("./FacebookDevices/Apple-iPhone-6s-Space-Gray.png"),
  "Apple iPhone 7 Gold": require("./FacebookDevices/Apple-iPhone-7-Gold.png"),
  "Apple iPhone 7 Jet Black": require("./FacebookDevices/Apple-iPhone-7-Jet-Black.png"),
  "Apple iPhone 7 Matte Black": require("./FacebookDevices/Apple-iPhone-7-Matte-Black.png"),
  "Apple iPhone 7 Plus Gold": require("./FacebookDevices/Apple-iPhone-7-Plus-Gold.png"),
  "Apple iPhone 7 Plus Jet Black": require("./FacebookDevices/Apple-iPhone-7-Plus-Jet-Black.png"),
  "Apple iPhone 7 Plus Matte Black": require("./FacebookDevices/Apple-iPhone-7-Plus-Matte-Black.png"),
  "Apple iPhone 7 Plus Rose Gold": require("./FacebookDevices/Apple-iPhone-7-Plus-Rose-Gold.png"),
  "Apple iPhone 7 Plus Silver": require("./FacebookDevices/Apple-iPhone-7-Plus-Silver.png"),
  "Apple iPhone 7 Rose Gold": require("./FacebookDevices/Apple-iPhone-7-Rose-Gold.png"),
  "Apple iPhone 7 Silver": require("./FacebookDevices/Apple-iPhone-7-Silver.png"),
  "Apple iPhone 8 Gold": require("./FacebookDevices/Apple-iPhone-8-Gold.png"),
  "Apple iPhone 8 Plus Gold": require("./FacebookDevices/Apple-iPhone-8-Plus-Gold.png"),
  "Apple iPhone 8 Plus Silver": require("./FacebookDevices/Apple-iPhone-8-Plus-Silver.png"),
  "Apple iPhone 8 Plus Space Grey": require("./FacebookDevices/Apple-iPhone-8-Plus-Space-Grey.png"),
  "Apple iPhone 8 Silver": require("./FacebookDevices/Apple-iPhone-8-Silver.png"),
  "Apple iPhone 8 Space Grey": require("./FacebookDevices/Apple-iPhone-8-Space-Grey.png"),
  "Apple iPhone SE Gold": require("./FacebookDevices/Apple-iPhone-SE-Gold.png"),
  "Apple iPhone SE Rose Gold": require("./FacebookDevices/Apple-iPhone-SE-Rose-Gold.png"),
  "Apple iPhone SE Silver": require("./FacebookDevices/Apple-iPhone-SE-Silver.png"),
  "Apple iPhone SE Space Gray": require("./FacebookDevices/Apple-iPhone-SE-Space-Gray.png"),
  "Apple iPhone X Silver": require("./FacebookDevices/Apple-iPhone-X-Silver.png"),
  "Apple iPhone X Space Grey": require("./FacebookDevices/Apple-iPhone-X-Space-Grey.png"),
  "Google Pixel 2 Clearly White": require("./FacebookDevices/Google-Pixel-2-Clearly-White.png"),
  "Google Pixel 2 Just Black": require("./FacebookDevices/Google-Pixel-2-Just-Black.png"),
  "Google PIxel 2 Kinda Blue": require("./FacebookDevices/Google-PIxel-2-Kinda-Blue.png"),
  "Google Pixel 2 XL Black and White": require("./FacebookDevices/Google-Pixel-2-XL-Black-and-White.png"),
  "Google Pixel 2 XL Just Black": require("./FacebookDevices/Google-Pixel-2-XL-Just-Black.png"),
  "Google Pixel Quite Black": require("./FacebookDevices/Google-Pixel-Quite-Black.png"),
  "Google Pixel Really Blue": require("./FacebookDevices/Google-Pixel-Really-Blue.png"),
  "Google Pixel Very Silver": require("./FacebookDevices/Google-Pixel-Very-Silver.png"),
  "HTC One A9 Black": require("./FacebookDevices/HTC-One-A9-Black.png"),
  "HTC One A9 White": require("./FacebookDevices/HTC-One-A9-White.png"),
  "HTC One M8 Black": require("./FacebookDevices/HTC-One-M8-Black.png"),
  "HTC One M8 Gold": require("./FacebookDevices/HTC-One-M8-Gold.png"),
  "HTC One M8 Silver": require("./FacebookDevices/HTC-One-M8-Silver.png"),
  "Huawei P8 Black": require("./FacebookDevices/Huawei-P8-Black.png"),
  "Huawei P8 White": require("./FacebookDevices/Huawei-P8-White.png"),
  "Microsoft Lumia 950 Black": require("./FacebookDevices/Microsoft-Lumia-950-Black.png"),
  "Microsoft Lumia 950 White": require("./FacebookDevices/Microsoft-Lumia-950-White.png"),
  "Microsoft Surface Pro 3": require("./FacebookDevices/Microsoft-Surface-Pro-3.png"),
  "Microsoft Surface Pro 4": require("./FacebookDevices/Microsoft-Surface-Pro-4.png"),
  "Motorola Moto E Black": require("./FacebookDevices/Motorola-Moto-E-Black.png"),
  "Motorola Moto E White": require("./FacebookDevices/Motorola-Moto-E-White.png"),
  "Motorola Moto G": require("./FacebookDevices/Motorola-Moto-G.png"),
  "Nexus 4": require("./FacebookDevices/Nexus-4.png"),
  "Nexus 5x": require("./FacebookDevices/Nexus-5x.png"),
  "Nexus 6P": require("./FacebookDevices/Nexus-6P.png"),
  "Nexus 9": require("./FacebookDevices/Nexus-9.png"),
  "Nokia 220 Black": require("./FacebookDevices/Nokia-220-Black.png"),
  "Nokia 220 Blue": require("./FacebookDevices/Nokia-220-Blue.png"),
  "Nokia 220 Red": require("./FacebookDevices/Nokia-220-Red.png"),
  "Nokia 220 White": require("./FacebookDevices/Nokia-220-White.png"),
  "Nokia 220 Yellow": require("./FacebookDevices/Nokia-220-Yellow.png"),
  "Nokia 230 Black": require("./FacebookDevices/Nokia-230-Black.png"),
  "Nokia 230 White": require("./FacebookDevices/Nokia-230-White.png"),
  "Nokia Asha 230 Black": require("./FacebookDevices/Nokia-Asha-230-Black.png"),
  "Nokia Asha 230 Blue": require("./FacebookDevices/Nokia-Asha-230-Blue.png"),
  "Nokia Asha 230 Green": require("./FacebookDevices/Nokia-Asha-230-Green.png"),
  "Nokia Asha 230 Red": require("./FacebookDevices/Nokia-Asha-230-Red.png"),
  "Nokia Asha 230 White": require("./FacebookDevices/Nokia-Asha-230-White.png"),
  "Nokia Asha 230 Yellow": require("./FacebookDevices/Nokia-Asha-230-Yellow.png"),
  "Nokia C3-00": require("./FacebookDevices/Nokia-C3-00.png"),
  "Samsung Galaxy Grand Prime Black": require("./FacebookDevices/Samsung-Galaxy-Grand-Prime-Black.png"),
  "Samsung Galaxy Grand Prime Gold": require("./FacebookDevices/Samsung-Galaxy-Grand-Prime-Gold.png"),
  "Samsung Galaxy Grand Prime White": require("./FacebookDevices/Samsung-Galaxy-Grand-Prime-White.png"),
  "Samsung Galaxy Note 5 Black": require("./FacebookDevices/Samsung-Galaxy-Note-5-Black.png"),
  "Samsung Galaxy Note 5 Gold": require("./FacebookDevices/Samsung-Galaxy-Note-5-Gold.png"),
  "Samsung Galaxy Note 5 Pink": require("./FacebookDevices/Samsung-Galaxy-Note-5-Pink.png"),
  "Samsung Galaxy Note 5 Silver Titanium": require("./FacebookDevices/Samsung-Galaxy-Note-5-Silver-Titanium.png"),
  "Samsung Galaxy Note 5 White": require("./FacebookDevices/Samsung-Galaxy-Note-5-White.png"),
  "Samsung Galaxy S Duos": require("./FacebookDevices/Samsung-Galaxy-S-Duos.png"),
  "Samsung Galaxy S3": require("./FacebookDevices/Samsung-Galaxy-S3.png"),
  "Samsung Galaxy S5 Black": require("./FacebookDevices/Samsung-Galaxy-S5-Black.png"),
  "Samsung Galaxy S5 White": require("./FacebookDevices/Samsung-Galaxy-S5-White.png"),
  "Samsung Galaxy S7 Black": require("./FacebookDevices/Samsung-Galaxy-S7-Black.png"),
  "Samsung Galaxy S7 Gold": require("./FacebookDevices/Samsung-Galaxy-S7-Gold.png"),
  "Samsung Galaxy S7 Silver": require("./FacebookDevices/Samsung-Galaxy-S7-Silver.png"),
  "Samsung Galaxy S7 White": require("./FacebookDevices/Samsung-Galaxy-S7-White.png"),
  "Samsung Galaxy S8 Arctic Silver": require("./FacebookDevices/Samsung-Galaxy-S8-Arctic-Silver.png"),
  "Samsung Galaxy S8 Coral Blue": require("./FacebookDevices/Samsung-Galaxy-S8-Coral-Blue.png"),
  "Samsung Galaxy S8 Maple Gold": require("./FacebookDevices/Samsung-Galaxy-S8-Maple-Gold.png"),
  "Samsung Galaxy S8 Midnight Black": require("./FacebookDevices/Samsung-Galaxy-S8-Midnight-Black.png"),
  "Samsung Galaxy S8 Orchid Gray": require("./FacebookDevices/Samsung-Galaxy-S8-Orchid-Gray.png"),
  "Samsung Galaxy Y Black": require("./FacebookDevices/Samsung-Galaxy-Y-Black.png"),
  "Samsung Galaxy Y White": require("./FacebookDevices/Samsung-Galaxy-Y-White.png")
};
