/* eslint-disable global-require */
export default {
  "Apple iPhone 5c Blue": require("./frames/Apple-iPhone-5c-Blue.png"),
  "Apple iPhone 5c Green": require("./frames/Apple-iPhone-5c-Green.png"),
  "Apple iPhone 5c Red": require("./frames/Apple-iPhone-5c-Red.png"),
  "Apple iPhone 5c White": require("./frames/Apple-iPhone-5c-White.png"),
  "Apple iPhone 5c Yellow": require("./frames/Apple-iPhone-5c-Yellow.png"),
  "Apple iPhone 5s Gold": require("./frames/Apple-iPhone-5s-Gold.png"),
  "Apple iPhone 5s Silver": require("./frames/Apple-iPhone-5s-Silver.png"),
  "Apple iPhone 5s Space Gray": require("./frames/Apple-iPhone-5s-Space-Gray.png"),
  "Apple iPhone 6s Gold": require("./frames/Apple-iPhone-6s-Gold.png"),
  "Apple iPhone 6s Rose Gold": require("./frames/Apple-iPhone-6s-Rose-Gold.png"),
  "Apple iPhone 6s Silver": require("./frames/Apple-iPhone-6s-Silver.png"),
  "Apple iPhone 6s Space Gray": require("./frames/Apple-iPhone-6s-Space-Gray.png"),
  "Apple iPhone 6s Plus Gold": require("./frames/Apple-iPhone-6s-Plus-Gold.png"),
  "Apple iPhone 6s Plus Rose Gold": require("./frames/Apple-iPhone-6s-Plus-Rose-Gold.png"),
  "Apple iPhone 6s Plus Silver": require("./frames/Apple-iPhone-6s-Plus-Silver.png"),
  "Apple iPhone 6s Plus Space Gray": require("./frames/Apple-iPhone-6s-Plus-Space-Gray.png"),
  "Apple iPhone 7 Gold": require("./frames/Apple-iPhone-7-Gold.png"),
  "Apple iPhone 7 Jet Black": require("./frames/Apple-iPhone-7-Jet-Black.png"),
  "Apple iPhone 7 Matte Black": require("./frames/Apple-iPhone-7-Matte-Black.png"),
  "Apple iPhone 7 Rose Gold": require("./frames/Apple-iPhone-7-Rose-Gold.png"),
  "Apple iPhone 7 Silver": require("./frames/Apple-iPhone-7-Silver.png"),
  "Apple iPhone 7 Plus Gold": require("./frames/Apple-iPhone-7-Plus-Gold.png"),
  "Apple iPhone 7 Plus Jet Black": require("./frames/Apple-iPhone-7-Plus-Jet-Black.png"),
  "Apple iPhone 7 Plus Matte Black": require("./frames/Apple-iPhone-7-Plus-Matte-Black.png"),
  "Apple iPhone 7 Plus Rose Gold": require("./frames/Apple-iPhone-7-Plus-Rose-Gold.png"),
  "Apple iPhone 7 Plus Silver": require("./frames/Apple-iPhone-7-Plus-Silver.png"),
  "Apple iPhone 8 Gold": require("./frames/Apple-iPhone-8-Gold.png"),
  "Apple iPhone 8 Silver": require("./frames/Apple-iPhone-8-Silver.png"),
  "Apple iPhone 8 Space Gray": require("./frames/Apple-iPhone-8-Space-Gray.png"),
  "Apple iPhone 8 Plus Gold": require("./frames/Apple-iPhone-8-Plus-Gold.png"),
  "Apple iPhone 8 Plus Silver": require("./frames/Apple-iPhone-8-Plus-Silver.png"),
  "Apple iPhone 8 Plus Space Gray": require("./frames/Apple-iPhone-8-Plus-Space-Gray.png"),
  "Apple iPhone SE Gold": require("./frames/Apple-iPhone-SE-Gold.png"),
  "Apple iPhone SE Rose Gold": require("./frames/Apple-iPhone-SE-Rose-Gold.png"),
  "Apple iPhone SE Silver": require("./frames/Apple-iPhone-SE-Silver.png"),
  "Apple iPhone SE Space Gray": require("./frames/Apple-iPhone-SE-Space-Gray.png"),
  "Apple iPhone X Silver": require("./frames/Apple-iPhone-X-Silver.png"),
  "Apple iPhone X Space Gray": require("./frames/Apple-iPhone-X-Space-Gray.png"),
  "Apple-Macbook-Gold": require("./frames/Apple-Macbook-Gold.png"),
  "Apple-Macbook-Space-Gray": require("./frames/Apple-Macbook-Space-Gray.png"),
  "Apple iPad Air 2 Gold": require("./frames/Apple-iPad-Air-2-Gold.png"),
  "Apple iPad Air 2 Silver": require("./frames/Apple-iPad-Air-2-Silver.png"),
  "Apple iPad Air 2 Space Gray": require("./frames/Apple-iPad-Air-2-Space-Gray.png"),
  "Apple iPad Mini 4 Gold": require("./frames/Apple-iPad-Mini-4-Gold.png"),
  "Apple iPad Mini 4 Silver": require("./frames/Apple-iPad-Mini-4-Silver.png"),
  "Apple iPad Mini 4 Space Gray": require("./frames/Apple-iPad-Mini-4-Space-Gray.png"),
  "Apple iPad Pro Gold": require("./frames/Apple-iPad-Pro-Gold.png"),
  "Apple iPad Pro Silver": require("./frames/Apple-iPad-Pro-Silver.png"),
  "Apple iPad Pro Space Gray": require("./frames/Apple-iPad-Pro-Space-Gray.png")
};
